// dia: 22/09/23 hs: 4:00am
package universidadgrupo33.vistas;

import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import universidadgrupo33.accesoADatos.AlumnoData;
import universidadgrupo33.accesoADatos.InscripcionData;
import universidadgrupo33.accesoADatos.MateriaData;
import universidadgrupo33.entidades.Alumno;
import universidadgrupo33.entidades.Inscripcion;
import universidadgrupo33.entidades.Materia;

public class JIFInscripciones extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };
    
    private DefaultTableModel modelo2 = new DefaultTableModel(){
    public boolean isCellEditable (int f, int c){               
        return false;
    }
    };
    
    AlumnoData alu = new AlumnoData();
    MateriaData mat = new MateriaData();
    InscripcionData ins = new InscripcionData();
    Alumno alu2 = new Alumno();
    Materia mat2 = new Materia();
    Inscripcion ins2 = new Inscripcion();

    // se usara esta variablñe para ser referencia del idALumno a buscar    
    int idAlumnoABuscar = 0;
    int idMateriaABuscar = 0;

    public JIFInscripciones() {
        initComponents();
        armarCabecera();
        armarCabecera2();
        // version VIEJA usando COMBOBOX
        //cargarComboBoxALumnos();
        this.setTitle("UNIVERSIDAD ULP - Formulario de Inscripción");
        jcbSeleccionAlumno.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jrbMateriasInscriptas = new javax.swing.JRadioButton();
        jrbjrbMateriasNoInscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtResultadoSeleccionAlumnos = new javax.swing.JTable();
        jbAnularInscripcion = new javax.swing.JButton();
        jbInscribir = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTConsultaAlumno = new javax.swing.JTable();
        jcbSeleccionAlumno = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Formulario de Inscripción");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Seleccione un alumno:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Listado de Materias");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Materias no Inscriptas");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Materias Inscriptas");

        grupoBotones.add(jrbMateriasInscriptas);
        jrbMateriasInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMateriasInscriptasActionPerformed(evt);
            }
        });

        grupoBotones.add(jrbjrbMateriasNoInscriptas);
        jrbjrbMateriasNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbjrbMateriasNoInscriptasActionPerformed(evt);
            }
        });

        jtResultadoSeleccionAlumnos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtResultadoSeleccionAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jtResultadoSeleccionAlumnos);

        jbAnularInscripcion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbAnularInscripcion.setText("Anular Inscripcion");
        jbAnularInscripcion.setEnabled(false);
        jbAnularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularInscripcionActionPerformed(evt);
            }
        });

        jbInscribir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbInscribir.setText("Inscribir");
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });

        jbSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jTConsultaAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTConsultaAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTConsultaAlumnoMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTConsultaAlumno);

        jcbSeleccionAlumno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbSeleccionAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSeleccionAlumnoActionPerformed(evt);
            }
        });
        jcbSeleccionAlumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcbSeleccionAlumnoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbAnularInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbSeleccionAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbMateriasInscriptas)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(43, 43, 43)
                        .addComponent(jrbjrbMateriasNoInscriptas)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcbSeleccionAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jrbMateriasInscriptas)
                            .addComponent(jrbjrbMateriasNoInscriptas)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbAnularInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAnularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularInscripcionActionPerformed
        if (idAlumnoABuscar != 0) {
            if (jtResultadoSeleccionAlumnos.getSelectedRow() != -1) {
                //idMateriaABuscar = Integer.parseInt((String) modelo.getValueAt(jtResultadoSeleccionAlumnos.getSelectedRow(), 0));
                idMateriaABuscar = (int) modelo.getValueAt(jtResultadoSeleccionAlumnos.getSelectedRow(), 0);
                // Lo imprimimos en pantalla
                //System.out.println(idMateriaABuscar);
                ins.borrarInscripcionMateriaAlumno(idAlumnoABuscar, idMateriaABuscar);
                //actualiza la visual de la tabla
                botonMateriasInscriptas();
            } else {
                JOptionPane.showMessageDialog(this, "No existe materia para anular");
            }
        }
    }//GEN-LAST:event_jbAnularInscripcionActionPerformed

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
        if (idAlumnoABuscar != 0) {
            if (jtResultadoSeleccionAlumnos.getSelectedRow() != -1) {
                //idMateriaABuscar = Integer.parseInt((String) modelo.getValueAt(jtResultadoSeleccionAlumnos.getSelectedRow(), 0));
                idMateriaABuscar = (int) modelo.getValueAt(jtResultadoSeleccionAlumnos.getSelectedRow(), 0);
                alu2.setIdAlumno(idAlumnoABuscar);
                mat2.setIdMateria(idMateriaABuscar);
                Inscripcion insc3 = new Inscripcion(alu2, mat2, 0);
                // Lo imprimimos en pantalla
                //System.out.println(idMateriaABuscar);
                ins.guardarInscripcion(insc3);
                //actualiza la visual de la tabla
                botonMateriasNoInscriptas();
            } else {
                JOptionPane.showMessageDialog(this, "No existe materia para anular");
            }
        }
    }//GEN-LAST:event_jbInscribirActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jrbjrbMateriasNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbjrbMateriasNoInscriptasActionPerformed
        if (idAlumnoABuscar!=0)
        {
           botonMateriasNoInscriptas();
        }
    }//GEN-LAST:event_jrbjrbMateriasNoInscriptasActionPerformed

    private void jrbMateriasInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMateriasInscriptasActionPerformed
        if (idAlumnoABuscar!=0)
        {        
           botonMateriasInscriptas();
        }     
    }//GEN-LAST:event_jrbMateriasInscriptasActionPerformed

    // version ANTERIOR con COMBOBOX
    /*
    private void jcbSeleccionAlumnoActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        alu2  = (Alumno) jcbSeleccionAlumno.getSelectedItem();                
        // verifica que no elija la primer linea del combobox que es solo titulo
        if (alu2.getIdAlumno() != 0) {
            idAlumnoABuscar = alu2.getIdAlumno();

            if (jrbMateriasInscriptas.isSelected()) {
                modelo.setRowCount(0);
                botonMateriasInscriptas();
            }

            if (jrbjrbMateriasNoInscriptas.isSelected()) {
                modelo.setRowCount(0);
                botonMateriasNoInscriptas();
            }            
        }else{
            modelo.setRowCount(0);        
            idAlumnoABuscar =0;
            jbInscribir.setEnabled(false);
            jbAnularInscripcion.setEnabled(false);
        }
        
        
        //System.out.println("x idAlumno a usar par buscar en Materias: "+idAlumnoABuscar);        
    }                                                  
    */
    
    private void jcbSeleccionAlumnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbSeleccionAlumnoKeyReleased
          borrarFilas();
        //      for (Materia mate: deTodoSa.listaProductos)
        for (Alumno alum : alu.listarAlumnosJTable(1)) {  
            
            if ((alum.getApellido()).contains((jcbSeleccionAlumno.getText())) ||
                     (alum.getNombre()).contains((jcbSeleccionAlumno.getText())) ||
                     (String.valueOf (alum.getDni())).contains((jcbSeleccionAlumno.getText()))) {
                modelo2.addRow(new Object[]{
                    alum.getIdAlumno(),
                    alum.getApellido(),
                    alum.getNombre(),
                    alum.getDni(),
                    alum.isActivo()
                });
            }

        }
        // PARA CONSULTAR SI LA TABLA ESTA VACIA O NO        
        if (jTConsultaAlumno.getRowCount() == 0)
        {
            JOptionPane.showMessageDialog(null, "No Existen Datos de Alumnos", "Advertencia",
            JOptionPane.WARNING_MESSAGE);
        }        
        else
        {        
            int linTabla = jTConsultaAlumno.getSelectedRow()+1;
            int colTabla = jTConsultaAlumno.getSelectedColumn();            
            Object valorTabla = jTConsultaAlumno.getValueAt(linTabla, 0);            
            Alumno alu2 = new Alumno();            
            alu2.setIdAlumno((Integer) jTConsultaAlumno.getValueAt(linTabla, 0));
            alu2.setApellido((String) jTConsultaAlumno.getValueAt(linTabla, 1));
            alu2.setNombre((String) jTConsultaAlumno.getValueAt(linTabla, 2));
            alu2.setDni((Integer) jTConsultaAlumno.getValueAt(linTabla, 3));
            alu2.setActivo(true);            
            if (alu2.getIdAlumno() != 0) {
                idAlumnoABuscar = alu2.getIdAlumno();
                if (jrbMateriasInscriptas.isSelected()) {
                    modelo.setRowCount(0);
                    botonMateriasInscriptas();
                }
                if (jrbjrbMateriasNoInscriptas.isSelected()) {
                    modelo.setRowCount(0);
                    botonMateriasNoInscriptas();
                }
            } else {
                modelo.setRowCount(0);
                idAlumnoABuscar = 0;
                jbInscribir.setEnabled(false);
                jbAnularInscripcion.setEnabled(false);
            }
        }   
    }//GEN-LAST:event_jcbSeleccionAlumnoKeyReleased

    private void jTConsultaAlumnoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTConsultaAlumnoMouseReleased

        JTable jTConsultaAlumno = (JTable) evt.getSource();
        int row = jTConsultaAlumno.getSelectedRow();
        int col = jTConsultaAlumno.getSelectedColumn();        
        // obligo a que se tome el nombre del Alumno para mostrar 
        Object data2 = (Object) jTConsultaAlumno.getValueAt(row, 1);        
        // y obligo a que se tome el codigo idMateria de la materia para buscar en las inscripciones x materia
        Object data1 = (Object) jTConsultaAlumno.getValueAt(row, 0);
        // asigno ese nombre elegido de la jtable a mi variable jTFMateriaAbuscar (jTextField) para buscar
        jcbSeleccionAlumno.setText(data2.toString());        
        //JOptionPane.showMessageDialog(null, "VVVVVV idMateria capturado desde la tabla es: "+data1);
        //JOptionPane.showMessageDialog(null, "VVVVVV nombre de la materia capturada desde la tabla es: "+data2);
        //JOptionPane.showMessageDialog(null, "VVVVVV nombre del jTFMateriaAbuscar es: "+jTFMateriaAbuscar.getText());        
    }//GEN-LAST:event_jTConsultaAlumnoMouseReleased

    private void jcbSeleccionAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSeleccionAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSeleccionAlumnoActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTConsultaAlumno;
    private javax.swing.JButton jbAnularInscripcion;
    private javax.swing.JButton jbInscribir;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTextField jcbSeleccionAlumno;
    private javax.swing.JRadioButton jrbMateriasInscriptas;
    private javax.swing.JRadioButton jrbjrbMateriasNoInscriptas;
    private javax.swing.JTable jtResultadoSeleccionAlumnos;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera(){
    modelo.addColumn("IdMateria");
    modelo.addColumn("Nombre de materia");
    modelo.addColumn("Año");
    jtResultadoSeleccionAlumnos.setModel(modelo);
    }
    
    private void armarCabecera2() {
        modelo2.addColumn("Id de Alumno");        
        modelo2.addColumn("Apellido");
        modelo2.addColumn("Nombre");
        modelo2.addColumn("Dni");
        jTConsultaAlumno.setModel(modelo2);
    }
    
    /*
    private void borrarFilas()
    {
        int filas = jtResultadoSeleccionAlumnos.getRowCount() - 1;
        System.out.println(jtResultadoSeleccionAlumnos.getCellEditor());
        System.out.println(filas);
        for (int i = filas; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }
    */
    
    /*
    // VERSION ANTERIOR CON COMBOBOX
    private void cargarComboBoxALumnos()
    {                   
        //System.out.println("Entro a llenar el combobox");
        // Vaciar el JComboBox
        jcbSeleccionAlumno.removeAllItems();
        // agrega una linea que diga -ELIJA UN ALUMNO DE LA LISTA-
        String fechaFalsa="21/09/2023";
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate fechaFalsaAPasar = LocalDate.parse(fechaFalsa, formato);
        Alumno aluTitulo = new Alumno(0,0,"-ELIJA UN ALUMNO DE LA LISTA-","",fechaFalsaAPasar,true);
        jcbSeleccionAlumno.addItem(aluTitulo); 
        // ahora agrega en el combobox los datos de alumnos recuperados desde sql        
        for(Alumno alum:alu.listarAlumnos(1)){      
            jcbSeleccionAlumno.addItem(alum); 
        }        
    }  
    */
    
    // VERSION NUEVA CON JTABLE
    public void cargarTablaAlumnosMateria(int idAlumnoBuscar) {                
        modelo.setRowCount(0);                
        for(Alumno alumn:alu.listarAlumnos(1)){      
           modelo.addRow(new Object []{
                   alumn.getIdAlumno(),
                   alumn.getDni(),
                   alumn.getApellido(),
                   alumn.getNombre(),
           });                    
        }        
    }  
    
    public void botonMateriasNoInscriptas() {
        jbInscribir.setEnabled(true);
        jbAnularInscripcion.setEnabled(false);        
        String hayMaterias="N";
        modelo.setRowCount(0);
        for (Materia mater : ins.obtenerMateriasNoCursadas(idAlumnoABuscar)) {
            modelo.addRow(new Object[]{mater.getIdMateria(),
                mater.getNombre(),
                mater.getAño()});
            hayMaterias="S";
        }
        if (hayMaterias=="N")
        {  
            jbInscribir.setEnabled(false);
            jbAnularInscripcion.setEnabled(false);
        }
    }
    
    public void botonMateriasInscriptas() {
        jbInscribir.setEnabled(false);
        jbAnularInscripcion.setEnabled(true);        
        String hayMaterias="N";
        modelo.setRowCount(0);        
        for(Materia mater:ins.obtenerMateriasCursadas(idAlumnoABuscar)){      
           modelo.addRow(new Object []{mater.getIdMateria(),
                   mater.getNombre(),
                   mater.getAño()});            
           hayMaterias="S";
        }
        if (hayMaterias=="N")
        {  
            jbInscribir.setEnabled(false);
            jbAnularInscripcion.setEnabled(false);
        }
    }    
    
    private void borrarFilas()
    {
        int filas = jTConsultaAlumno.getRowCount() - 1;
        for (int i = filas; i >= 0; i--) {
            modelo2.removeRow(i);
        }
    }
    
    
    
    
}
