// dia: 18/09/23 hs: 15:23
package universidadgrupo33.vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author Multi
 */
public class UsuarioPassw extends javax.swing.JInternalFrame {
    static int IngresarMenu=0;    
    
    public UsuarioPassw() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIcono = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jTextFieldUser = new javax.swing.JTextField();
        jBIniciarSesion = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadgrupo33/vistas/usuario03.png"))); // NOI18N
        getContentPane().add(jLabelIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, -40, 250, 510));

        jLabel1.setBackground(new java.awt.Color(51, 0, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel2.setBackground(new java.awt.Color(51, 0, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 130, -1));

        jPassword.setBackground(new java.awt.Color(0, 51, 153));
        jPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 300, 30));

        jTextFieldUser.setBackground(new java.awt.Color(0, 51, 153));
        jTextFieldUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldUser.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 300, 30));

        jBIniciarSesion.setBackground(new java.awt.Color(255, 255, 102));
        jBIniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBIniciarSesion.setForeground(new java.awt.Color(0, 51, 204));
        jBIniciarSesion.setText("Iniciar Sesion");
        jBIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jBIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 180, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadgrupo33/vistas/fondo01.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jTextFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserActionPerformed

    private void jBIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIniciarSesionActionPerformed
        // programsr para que haga una tarea en -Iniciar Sesion-
        //JLabel etiqueta = new JLabel("");
        //add(etiqueta);
        //etiqueta.setText(input.getText());
        //JTextField textField = new JTextField();
        IngresarMenu=0;

        String usua = jTextFieldUser.getText();
        String pasw = jPassword.getText();
        //System.out.println("- MENU del Trabajo - usuario: "+usua+" password: "+pasw);
        if (usua.equals("GRUPO33")){
            //System.out.println("EL USUARIO ES CORRECTO...");
            IngresarMenu++;
        }
        else{
            //System.out.println("ERROR -- EL USUARIO EN INCORRECTO...");
            //JOptionPane.showMessageDialog(this, "ERROR -- EL USUARIO EN INCORRECTO...");
        }
        if (pasw.equals("GRUPO332023")){
            //System.out.println("LA CONTRASEÑA ES CORRECTA...");            
            IngresarMenu++;
        }
        else{
            //System.out.println("ERROR -- LA CONTRASEÑA ES ERRORNEA...");
            //JOptionPane.showMessageDialog(this, "ERROR -- LA CONTRASEÑA ES ERRORNEA...");
        }
        if (IngresarMenu==2)
        {
            JOptionPane.showMessageDialog(this, "<<<<< B I E N V E N I D O >>>>>");
            //System.out.println("ingresooooo");
            //System.exit(0);
            /*
            jdpEscritorio.removeAll();
            jdpEscritorio.repaint();
            UsuarioPassw usuPas = new UsuarioPassw();
            usuPas.setVisible(true);
            jdpEscritorio.add(usuPas);
            jdpEscritorio.moveToFront(usuPas);
            */
            this.dispose();            
        }else {
            JOptionPane.showMessageDialog(this, "<<< ERROR >>> al ingresar USUARIO y/o PASSWORD....");
        }
    }//GEN-LAST:event_jBIniciarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
